on:
  push:
  pull_request:

name: CI

jobs:

  firmware:
    name: Build and test firmware
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.55.0
          override: true
      - name: Run check
        run: cd firmware && cargo check
      - name: Run tests
        run: cd firmware && cargo test --target x86_64-unknown-linux-gnu --tests

  rustfmt:
    name: Check code formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.55.0
          components: rustfmt
          override: true
      - run: cd firmware && cargo fmt -- --check
